<?php
require_once "./controllers/headerController.php";

?>

<header>
    <div id="logoIconsContainer">
        <h1 id="logo">Tp site e-commerce</h1>
        <div id="iconsContainer"></div>
    </div>
    
    <nav>
        <ul>
            <li><a href="/">Accueil</a></li>
            <?php if($_SESSION["connected"]) : ?>
                <li><a href="/dashbord">Dashbord</a></li>
            <?php endif;?>
            <li><a href=<?= $linkConnectionLink ?>><?= $btnConnexionDisplay ?></a></li>
        </ul>
    </nav>
</header>