<section>
    <h2>Tous les produits</h2>
    <div id="containerProducts">
        <?php foreach ($products as $product): ?>
            <div class="containerProduct">
                <img src="<?= $product["imgPath"] ?>" alt="image produit">
                <h3><?= $product["title"] ?></h3>
                <p><?= $product["description"] ?></p>
                <p><?= $product["price"] ?> €</p>
            </div>
        <?php endforeach; ?>
    </div>
</section>