<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Site e-commerce</title>
    <link rel="stylesheet" href="./views/assets/css/header.css">
    <link rel="stylesheet" href="./views/assets/css/footer.css">
    <link rel="stylesheet" href="./views/assets/css/index.css">
    <link rel="stylesheet" href="./views/assets/css/config.css">
</head>

<body>
    <?php
    include_once("./views/header.phtml");
    ?>
    <main>
    <?php
    include_once("./views/" . $page . ".phtml");
    ?>
    </main>
    <?php
    include_once("./views/footer.phtml");
    ?>
</body>

</html>