<form action="./controllers/connexionUserController.php" method="post">
    <label for="username">Nom d'utilisateur : </label>
    <input type="text" name="username" id="username">
    <br>
    <label for="password">Mot de passe : </label>
    <input type="password" name="password" id="password">
    <br>
    <button type="submit">Se connecter</button>
</form>
<button><a href="/newUser">Créer un nouveau utilisateur</a></button>