<?php

require("./controllers/homeController.php");

?>
<section>
    <h2>Tous les produits</h2>
    <div id="containerProducts">
        <?php foreach ($products as $product): ?>
            <div class="upperLayer">
                <h3><?= $product["title"] ?></h3>
            <div class="containerProduct">
                
                <p class="description"><?= $product["description"] ?></p>
                <div class="imgContainer">
                <img src="./views/assets/imgProducts/<?= $product["imgPath"] ?>.jpg" alt="image produit">
                </div>
                
                <p class="price"><?= $product["price"] ?> €</p>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</section>