<form action="./controllers/createNewUserController.php" method="post">
    <label for="username">Nom utilisateur</label>
    <input type="text" name="username" id="username">
    <br>
    <label for="password">Mot de passe</label>
    <input type="text" name="password" id="password">
    <br>
    <label for="">Répéter mot de passe</label>
    <input type="text" name="passwordRepeat" id="passwordRepeat">
    <br>
    <button type="submit">Créer</button>
</form>