<form action="./controllers/createNewProductController.php" method="post">
<label for="">Nom du produit</label>
<input type="text" name="title" id="nameUser">
<br>
<label for="">Description du produit</label>
<input type="text" name="description" id="nameUser">
<br>
<label for="">Prix du produit</label>
<input type="text" name="price" id="nameUser">
<br>
<label for="">Chemin de l'image</label>
<input type="text" name="imgPath" id="nameUser">
<br>
<button type="submit">Ajouter</button>
</form>